# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on: push

name: pkgdown

env:
  CMDSTAN: /home/runner/work/PKPDposterior/PKPDposterior/Torsten/cmdstan
  STAN_PATH: /home/runner/work/PKPDposterior/PKPDposterior/Torsten

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - name: Install Torsten
        run: |
          git clone https://github.com/metrumresearchgroup/Torsten.git
          cd Torsten/cmdstan
          make build

      # - uses: r-lib/actions/setup-r-dependencies@v1
      #   with:
      #     extra-packages: pkgdown
      #     needs: website

      # - name: Deploy package
      #   run: |
      #     git config --local user.name "$GITHUB_ACTOR"
      #     git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
      #     Rscript -e 'pkgdown::build_site()'
